### ISSUE TITLE
Agenda items next board meeting

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/organisational#56]
Proposed agenda points
* [x] officer roles (see https://github.com/uio-carpentry/governance/pull/21)
* [x] role of the board (see https://github.com/uio-carpentry/governance/issues/14)
   * [x] including start thinking about long-term directions for Carpentry@UiO
* [x] process for governance documents review (see #53)
* [x] review of the mailing lists (see https://github.com/uio-carpentry/organisational/blob/master/board/onboarding.md#carpentryuio-mailing-lists)
* [x] instructor training spots 2020-2021: determine process and criteria to find candidates to offer this training

By email:
* [x] do we want to ask permission from all Carpentry@UiO instructor's to publish their names somewhere, for example on https://governance.readthedocs.io/en/latest/intro.html#carpentry-uio-instructors or elsewhere (see https://github.com/uio-carpentry/governance/issues/1)

Postponed
* [x] what constitutes an 'official' UiO@Carpentry workshop?

**Comment by arockenberger** [comment]
Let's move the remaining open agenda items to a new Issue for the next meeting agenda!

**Comment by arockenberger** [comment]
Postponed agenda items (the two lower ones) have been moved to the [agenda for the 2020-08-27 meeting](https://github.com/uio-carpentry/organisational/blob/master/meetings/200827_board-meeting.md). Closing the issue.
